### ISSUE TITLE
Protocol umap: TypeError: check_array() got an unexpected keyword argument 'ensure_all_finite'

### ISSUE THREAD

**Issue by ScraperMan2002** [sacdallago/bio_embeddings#256]
## Metadata
|key|value|
|--|--|
|**version**|0.2.3|
|**cuda**|False|

## Parameter
|key|value|
|--|--|
type|project
protocol|umap
depends_on|stage_1

## Traceback
```
Traceback (most recent call last):
  File "/home/youjun/bio_embeddings/venv/lib64/python3.9/site-packages/bio_embeddings/utilities/pipeline.py", line 322, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "/home/youjun/bio_embeddings/venv/lib64/python3.9/site-packages/bio_embeddings/project/pipeline.py", line 204, in run
    result_kwargs = PROTOCOLS[kwargs["protocol"]](file_manager, result_kwargs)
  File "/home/youjun/bio_embeddings/venv/lib64/python3.9/site-packages/bio_embeddings/project/pipeline.py", line 113, in umap
    projected_embeddings = umap_reduce(reduced_embeddings, **result_kwargs)
  File "/home/youjun/bio_embeddings/venv/lib64/python3.9/site-packages/bio_embeddings/project/umap.py", line 16, in umap_reduce
    transformed_embeddings = UMAP(**umap_params).fit_transform(embeddings)
  File "/home/youjun/bio_embeddings/venv/lib64/python3.9/site-packages/umap/umap_.py", line 2935, in fit_transform
    self.fit(X, y, ensure_all_finite, **kwargs)
  File "/home/youjun/bio_embeddings/venv/lib64/python3.9/site-packages/umap/umap_.py", line 2372, in fit
    X = check_array(
TypeError: check_array() got an unexpected keyword argument 'ensure_all_finite'
```

**Comment by ScraperMan2002** [comment]
This is another dependency version mismatch problem. The error comes from UMAP calling a function in scikit-learn whose API changed.

Take a look at this:

TypeError: check_array() got an unexpected keyword argument 'ensure_all_finite'

Inside UMAP, it calls:

check_array(..., ensure_all_finite=...)

But version 1.2.2 of scikit-learn does not support that argument.

This means to fix it, we need to upgrade scikit-learn slightly so it matches UMAP.

This command:

pip install "scikit-learn>=1.6"

Works well with version 0.5.11 umap-learn.
